//! Small status-icon bitmaps: ground/rocket header glyphs, signal bars,
//! charging bolt. Bit-packed (MSB-first per row) data generated from
//! `icons.py`'s ASCII-art tuples by `scratchpad/gen_bitmaps.py` (not
//! hand-transcribed) and verified to round-trip byte-for-byte against the
//! original -- regenerate from there if the upstream Python art changes,
//! don't hand-edit. `icons.rs` has the drawing functions that use these.

// Generated by scratchpad/gen_bitmaps.py from icons.py's small bitmaps.
// Do not hand-edit -- regenerate from icons.py instead.

pub const GROUND_W: usize = 10;
pub const GROUND_H: usize = 10;
pub static GROUND_BITS: [u8; 20] = [
    0x0c, 0x00, 0x12, 0x00, 0x21, 0x00, 0x5e, 0x80, 0xa1, 0x40, 0xa1, 0x40, 0x5e, 0x80, 0x21, 0x00,
    0x12, 0x00, 0x0c, 0x00,
];

pub const ROCKET_ICON_W: usize = 8;
pub const ROCKET_ICON_H: usize = 10;
pub static ROCKET_ICON_BITS: [u8; 10] = [
    0x18, 0x3c, 0x3c, 0x3c, 0x3c, 0x3c, 0x7e, 0xff, 0xff, 0xff,
];

pub const BOLT_W: usize = 6;
pub const BOLT_H: usize = 10;
pub static BOLT_BITS: [u8; 10] = [
    0x30, 0x30, 0x60, 0x60, 0xfc, 0x38, 0x18, 0x30, 0x30, 0x60,
];

pub const SIGNAL_W: usize = 8;
pub const SIGNAL_H: usize = 5;
pub static SIGNAL_BARS_0: [u8; 5] = [
    0x00, 0x00, 0x00, 0x00, 0xff,
];

pub static SIGNAL_BARS_1: [u8; 5] = [
    0x00, 0x00, 0x00, 0xc0, 0xff,
];

pub static SIGNAL_BARS_2: [u8; 5] = [
    0x00, 0x00, 0x30, 0xf0, 0xff,
];

pub static SIGNAL_BARS_3: [u8; 5] = [
    0x00, 0x0c, 0x3c, 0xfc, 0xff,
];

pub static SIGNAL_BARS_4: [u8; 5] = [
    0x03, 0x0f, 0x3f, 0xff, 0xff,
];

