name: "LaunchControl CI Tests"
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    name: ci tests
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix run --accept-flake-config .#check
